# General
name: "Biocomputing 2017"
description: "Peer-led Introduction to Computational Biology"
baseurl: "/Biocomputing_Spring2017"
future: true


markdown: kramdown
highlighter: rouge
#redcarpet:
#    extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]


# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
